export var categories=[
    'ROUND TOURS','EXOTIC,RELAXING,SUN-KISSED','WILDLIFE','DISCOVERY','ADVENTURE,ADRENALINE,AWAKENING',
    'CULTURE,HERITAGE,SPIRITUALITY','SERENE,RETREAT,SANCTUARY','PURIFY,CLEANSE,REJUVENATE','CONNECT,ROMANCE,DREAM'
]